// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUnKlfrCS4JqhupmaDmGOtl_C_nvo3kIU',
    appId: '1:461478841243:android:9d5368fe28ecb789496f3e',
    messagingSenderId: '461478841243',
    projectId: 'safe-trip-3cfcf',
    databaseURL: 'https://safe-trip-3cfcf-default-rtdb.firebaseio.com',
    storageBucket: 'safe-trip-3cfcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXvMSd7RDCeqaPmLhym6sm35nYFVPUEKk',
    appId: '1:461478841243:ios:a87139aa7643af39496f3e',
    messagingSenderId: '461478841243',
    projectId: 'safe-trip-3cfcf',
    databaseURL: 'https://safe-trip-3cfcf-default-rtdb.firebaseio.com',
    storageBucket: 'safe-trip-3cfcf.appspot.com',
    iosBundleId: 'com.safetrip.safeTripDriverApp',
  );
}
